import Head from "next/head";
import styles from "./layout.module.css";
import Link from "next/link";
import Image from "next/image";
import React, { useState, useEffect } from "react";

export default function Layout({ children }) {
  const [showTopBtn, setShowTopBtn] = useState(false);
  const ScrollToTop = () => {
    console.log(window.scrollY);
    window.scroll({
      top: 0,
      behavior: "smooth",
    });
  };
  const Scroll = () => {
    if (window.scrollY > 1000) {
      setShowTopBtn(true);
      console.log("success");
  } else {
    setShowTopBtn(false);
    console.log("fail");
  }
  }

  const getButtonStyle = () => {
    if (showTopBtn) return styles.btn;
    else return styles.btn.active;
  }
  return (
    <>
      <Head>
        <title>香港導盲犬協會 HKGDA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-100x100.jpg" />
      </Head>
      <div onMouseOver={Scroll}>
      <main className={styles.main}>
        {/* <h1 className={styles.title}>
            <Link href="/">
              HKGDA
            </Link>
          </h1> */}
        <div className={styles.header}>
          <ul>
            <li className={styles.headerdivder}></li>
            <li>
              <Link href="https://www.igdf.org.uk/">
                <a>
                  <Image
                    priority
                    src="/IGDF.Logo_.Colours.jpg"
                    height={80}
                    width={80}
                    alt={"IGDF"}
                  />
                </a>
              </Link>
              <Link href="https://aai-int.org/">
                <a>
                  <Image
                    priority
                    src="/68248661_2501539039908994_1390522419726254080_n.jpg"
                    height={80}
                    width={80}
                    alt={"AAI"}
                  />
                </a>
              </Link>
              <Link href="https://assistancedogsinternational.org/">
                <a>
                  <Image
                    priority
                    src="/AAIILogoLarge-1024x442.jpg"
                    height={80}
                    width={150}
                    alt={"AAII"}
                  />
                </a>
              </Link>
            </li>
            <li className={styles.headerdivder}></li>
          </ul>
        </div>
        <div className={styles.content}>{children}</div>
      </main>
      <div className={styles.footlay} /*onMouseOver={Scroll}*/>
        <div className={styles.imagebox}>
          <div className={styles.image}>
            <Image
              priority
              src="/guidedog_footer.png"
              height={159.08}
              width={1050}
              alt={"Footer"}
            />
          </div>
        </div>
        <div className={styles.footer}>
          <div className={styles.footer_p1}>
            <p className={styles.footHead}>Hong Kong Guide Dogs Association</p>
            <p className={styles.footContent}>
              Address: Jockey Club Education and Training Centre Unit No.1,
              Podium, Car Park Block, Tsui Ping (South) Estate, 18 Tsui Ping
              Road, Kwun Tong, Kowloon, Hong Kong
              <br />© 2022 Hong Kong Guide Dogs Association All Rights Reserved.
              Registered Charity Number: 91/11219&nbsp;
              <Link href="https://www.guidedogs.org.hk/contact-us/">
                <a>Accessibility Statement</a>
              </Link>
            </p>
          </div>
          <div>
            <p className={styles.footSub}>Subscribe us: </p>
            <div>
              <form>
                <div className={styles.input_field}>
                  <label>Email: </label>
                  <lable className={styles.screen_reader_text}>Email:</lable>
                  <input
                    type="text"
                    name="email"
                    className={styles.email}
                  ></input>
                </div>
                <div className={styles.input_field}>
                  <button type="button" className={styles.Sub}>
                    Subscribe{" "}
                  </button>
                  {/* <div className={styles.submit_loader}>
                  <Image
                    priority
                    src="/ajax_loader.gif"
                    width={20}
                    height={20}
                    alt={"Loading"}
                  />
                </div> */}
                </div>
              </form>
            </div>
          </div>
        </div>
        <div>
          <button
            id="btn"
            type="button"
            className={getButtonStyle()}
            onClick={ScrollToTop}
          >
            &#1997;
          </button>
        </div>
      </div>
      <div className={styles.btmfoot}>
        <div className={styles.btmfoottext}>
          <div>
            Hong Kong Guide Dogs Association Tel: (852) 31881736 / (852)
            31883849 Fax: (852) 31883647 Email: info@guidedogs.org.hk
          </div>
        </div>
      </div>
      </div>
    </>
  );
}
